[package]
name = "ffsvm"
version = "0.2.1"
authors = ["Ralf Biedert <rb@xr.io>"]
readme = "README.adoc"
categories = ["science", "algorithms"]
license = "MIT"
exclude = [
    "docs/*",
]


[dependencies]
#faster = "^0.4.3"
faster = { git="https://github.com/ralfbiedert/faster", rev="194ad1f4e19ca9835eab259778f934a85e6b8ff6" }  
#faster = { path="../faster" }  
rand = "^0.3"
rayon = "0.9"
#nom = "4.0.0-alpha2"
nom = { git="https://github.com/Geal/nom", rev="9c44bd9790dce9d7c282e4cc692ecc1fddcd5590" }  
#clippy = {version = "*", optional = true}

[lib]
name = "ffsvm"
path = "src/lib.rs"
crate-type = [ "rlib", "dylib" ]

[[bin]]
name = "ffsvm"
path = "src/bin.rs"


[profile.release]
opt-level = 3
debug = false
lto = true
