[package]
name = "ffsvm"
version = "0.2.3"
authors = ["Ralf Biedert <rb@xr.io>"]
readme = "README.adoc"
categories = ["science", "algorithms"]
license = "MIT"
exclude = [
    "docs/*",
]


[dependencies]
faster = { git="https://github.com/ralfbiedert/faster", rev="8a86e1b7f75065b44bd9caab643468d9a5794579" }  
rand = "^0.3"
rayon = "0.9"
nom = { git="https://github.com/Geal/nom", rev="9c44bd9790dce9d7c282e4cc692ecc1fddcd5590" }  


[lib]
name = "ffsvm"
path = "src/lib.rs"
crate-type = [ "rlib", "dylib" ]

[[bin]]
name = "ffsvm"
path = "src/bin.rs"


[profile.release]
opt-level = 3
lto = true
