[package]
name = "ffsvm"
version = "0.1.0"
authors = ["Ralf Biedert <rb@xr.io>"]
publish = false
readme = "README.md"
categories = ["science", "algorithms"]
license = "BSD-2-Clause"


[dependencies]
faster = "^0.2"
rand = "^0.3"
itertools = "^0.7"
rayon = "0.9"
nom = { git = "https://github.com/Geal/nom" }


[lib]
name = "ffsvm"
path = "src/lib.rs"
crate-type = [ "rlib", "dylib" ]

[[bin]]
name = "ffsvm"
path = "src/bin.rs"


[profile.release]
opt-level = 3
debug = false
lto = true
