[package]
name = "ffsvm"
description="A libSVM compatible support vector machine, but 10x faster, for real-time classification, like games or VR."
version = "0.3.0"
repository = "https://github.com/ralfbiedert/ffsvm-rust"
authors = ["Ralf Biedert <rb@xr.io>"]
readme = "README.adoc"
categories = ["science", "algorithms"]
license = "MIT"
exclude = [
    "docs/*",
]

[dependencies]
faster = { git="https://github.com/ralfbiedert/faster", rev="dd05201291e9f408d6755fdf4bd23ad93dfe7b96" }  
# faster = { path = "../faster-ralfbiedert" }  
rand = "0.5"
nom = "4.0"  
serde = { version = "1.0", optional = true, features = ["derive"] }

[lib]
name = "ffsvm"
path = "src/lib.rs"
crate-type = [ "rlib" ]

[profile.release]
opt-level = 3
lto = true
