cargo-features = ["edition"]

[package]
name = "ffsvm"
description="A libSVM compatible support vector machine (RBF), but up to 10x faster, for games or VR."
version = "0.5.0"
repository = "https://github.com/ralfbiedert/ffsvm-rust"
authors = ["Ralf Biedert <rb@xr.io>"]
readme = "README.md"
categories = ["science", "algorithms"]
keywords = ["svm", "libsvm"]
license = "MIT"
edition = "2018"
exclude = [
    "docs/*",
]

[badges]
travis-ci = { repository = "ralfbiedert/ffsvm-rust" }
maintenance = { status = "experimental" }


[dependencies]
simd_aligned = "0.1.1"
packed_simd = "0.1"
rand = "0.5"
nom = "4.0"
# serde = { version = "1.0", optional = true, features = ["derive"] }

[lib]
name = "ffsvm"
path = "src/lib.rs"
crate-type = [ "rlib" ]

[profile.release]
opt-level = 3
lto = true
