[package]
name = "ffsvm"
version = "0.2.4"
authors = ["Ralf Biedert <rb@xr.io>"]
readme = "README.adoc"
categories = ["science", "algorithms"]
license = "MIT"
exclude = [
    "docs/*",
]


[dependencies]
faster = { git="https://github.com/ralfbiedert/faster", rev="8a86e1b7f75065b44bd9caab643468d9a5794579" }  
rand = "0.4"
rayon = "1.0"
nom = "4.0.0-beta3"  


[lib]
name = "ffsvm"
path = "src/lib.rs"
crate-type = [ "rlib", "dylib" ]

[[bin]]
name = "ffsvm"
path = "src/bin.rs"


[profile.release]
opt-level = 3
lto = true
