cargo-features = ["edition"]

[package]
name = "ffsvm"
description="A libSVM compatible support vector machine, but 10x faster, for real-time classification, like games or VR."
version = "0.3.0"
repository = "https://github.com/ralfbiedert/ffsvm-rust"
authors = ["Ralf Biedert <rb@xr.io>"]
readme = "README.adoc"
categories = ["science", "algorithms"]
license = "MIT"
edition = "2018"
exclude = [
    "docs/*",
]


[dependencies]
faster = { git="https://github.com/AdamNiederer/faster", rev="2eaa4c9c9b617f170a43a8f6e669fcc77e553e23" }  
# faster = { path = "../faster-ralfbiedert" }  
rand = "0.5"
nom = "4.0"  
serde = { version = "1.0", optional = true, features = ["derive"] }

[lib]
name = "ffsvm"
path = "src/lib.rs"
crate-type = [ "rlib" ]

[profile.release]
opt-level = 3
lto = true
