[package]
name = "ffsvm"
version = "0.2.0"
authors = ["Ralf Biedert <rb@xr.io>"]
readme = "README.adoc"
categories = ["science", "algorithms"]
license = "MIT"
exclude = [
    "docs/*",
]


[dependencies]
faster = "^0.4.1"
rand = "^0.3"
rayon = "0.9"
nom = "4.0.0-alpha1"
#clippy = {version = "*", optional = true}

[lib]
name = "ffsvm"
path = "src/lib.rs"
crate-type = [ "rlib", "dylib" ]

[[bin]]
name = "ffsvm"
path = "src/bin.rs"


[profile.release]
opt-level = 3
debug = false
lto = true
