[package]
name = "ffsvm"
version = "0.1.0"
authors = ["Ralf Biedert <rb@xr.io>"]
publish = false
readme = "README.adoc"
categories = ["science", "algorithms"]
license = "BSD-2-Clause"
exclude = [
    "docs/*",
]


[dependencies]
faster = { git = "https://github.com/AdamNiederer/faster" }
rand = "^0.3"
itertools = "^0.7"
rayon = "0.9"
nom = { git = "https://github.com/Geal/nom" }
#clippy = {version = "*", optional = true}

[lib]
name = "ffsvm"
path = "src/lib.rs"
crate-type = [ "rlib", "dylib" ]

[[bin]]
name = "ffsvm"
path = "src/bin.rs"


[profile.release]
opt-level = 3
debug = false
lto = true
